### ISSUE TITLE
how to support Swift2.3 ？

### ISSUE THREAD

**Issue by Chakery** [danielrhodes/Swift-ActionCableClient#10]
XCode 8
Swift 2.3

I got the following error. help please.

![image](https://cloud.githubusercontent.com/assets/9679029/18821478/f867641a-83d8-11e6-8126-289e39c316d7.png)

**Comment by Chakery** [comment]
the Starscream tag 1.1.4 for Swift 2.3 support.

**Comment by wuxiao356** [comment]
@Chakery Got the same issue here. But the framework depends on 1.1.3 of Starscream. I was trying to change Starscream version from Podfile. But it did not work. Did you figure out how to fix it?

**Comment by wuxiao356** [comment]
Is it possible to change the framework's dependency on Starscream to 1.1.4?

**Comment by Chakery** [comment]
I can't fix it. I also tried to depends 1.1.4 of Starscream, but failed.

**Comment by wuxiao356** [comment]
I solved my problem by following this.

1.  Try 0.1.6 version `pod 'ActionCableClient', '0.1.6'`
2.  Add following at the end of Podfile
`post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end`
3. Do `pod install`
4. After you reopen the project, the Xcode will give you two errors for the library's code, just fix it using the suggestion.

**Comment by Chakery** [comment]
Thx，I'll try that now.

**Comment by danielrhodes** [comment]
@wuxiao356 Hey could you make a pull request with that and I will put it in? Wasn't planning on supporting 2.3 but if it is straightforward I can.

**Comment by danielrhodes** [comment]
So just a note here: the upcoming XCode 8.2 is going to be the last version to support Swift 2.3. Thus, I am not going to support it since its lifetime has been so short.
