### ISSUE TITLE
swift 3 support

### ISSUE THREAD

**Issue by jarredszabadi** [danielrhodes/Swift-ActionCableClient#14]
upon attempting to use swift 3 via pods

pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'swift3'
pod 'ActionCableClient', :git => 'https://github.com/danielrhodes/Swift-ActionCableClient', :branch => 'swift3'

xcode 8 requested that it convert the starscream library to latest syntax. I believe that the switft3 branch here can use the 2.0.0 release of starscream to fix this issue. 

Until then using ActionCableClient for swift 3 doesn't seem doable on Xcode8.

Hopefully I'm wrong and there is a solution for this?

Cheers!

**Comment by danielrhodes** [comment]
This is complete. Update to 0.2.1.

**Comment by bitomule** [comment]
When would swift3 branch get merged into master? Is there a way to user Carthage and Swift3 branch?
