### ISSUE TITLE
Module compiled with Swift 3.0

### ISSUE THREAD

**Issue by bitomule** [danielrhodes/Swift-ActionCableClient#15]
Trying to use master branch with Xcode 3.1 and got this error:

`Module compiled with Swift 3.0: cannot be imported in Swift 3.0.1`

**Comment by danielrhodes** [comment]
Yeah let me recompile it for 3.0.1.

In the mean time, use `--no-use-binaries` as I'm sure you're seeing this in other libraries as well.

**Comment by danielrhodes** [comment]
Fixed.
