### ISSUE TITLE
Unable to update to latest version

### ISSUE THREAD

**Issue by danipralea** [danielrhodes/Swift-ActionCableClient#17]
Hello and thanks for the library!
I am having issues updating the library to its latest version - 0.2.1

Not specifying the version - installs the **ActionCableClient** to 0.1.4
If I set it as `pod 'ActionCableClient', '0.2.1'`, I get the following error:

```
[!] Unable to satisfy the following requirements:

- `ActionCableClient (= 0.2.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ActionCableClient (= 0.2.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**UPDATE**:
I ended up using `pod 'ActionCableClient', :git=> 'https://github.com/danielrhodes/Swift-ActionCableClient', :branch => '0.2.2'` which fixed it, it but I'm guessing something is wrong with the default install.

**Comment by danielrhodes** [comment]
Try it again. I think what happened is the podspec got pushed to Cocoapods (the service) from the 0.2.2 branch, whereas the gem itself looks to the master branch for the same podspec.

**Comment by danipralea** [comment]
Daniel, thank you for your response. I did tried again and I'm being met with the following error message:
![screenshot 2016-11-12 01 59 58](https://cloud.githubusercontent.com/assets/768893/20233760/ce52d976-a87b-11e6-8811-270562cfad9f.png)

**Comment by danielrhodes** [comment]
I'm not sure why this is happening. But I think it is because Starscream didn't release their pod for 2.0.1 correctly (no branch named with the release). So I am going to push 0.2.3 which hopefully resolves this by pinning the spec to 2.0.0.

**Comment by danielrhodes** [comment]
@danipralea Try it out and see if it works for you.

**Comment by danipralea** [comment]
I will

**Comment by danipralea** [comment]
I'm simply using this now and so far it seems to work.

```
# Web sockets
pod 'ActionCableClient', :git=> 'https://github.com/danielrhodes/Swift-ActionCableClient', :branch => '0.2.2'
```
