### ISSUE TITLE
Sending un-supported action

### ISSUE THREAD

**Issue by danipralea** [danielrhodes/Swift-ActionCableClient#18]
Hello, I have successfully implemented the library, but on the course of doing that, I kept sending invalid actions to the server. The server did acknowledge that by echoing `
Unable to process ChannelEventsChannel#entity_typing)` while I was sending `room.action("entity_typing")`

Basically I was sending an action not recognised by the server. It was ok for me, cause I had server support, but it shouldn't have reached to that and I should have known from the start that I was sending an invalid action by receiving an error when sending it.

Just a thought.

**Comment by danielrhodes** [comment]
In that case, I would recommend a REST API. ActionCable, but more generally sockets, do not work that way unless there is such a contract in the protocol used.

**Comment by danipralea** [comment]
no worries. I thought the underlying library, Starscream has this capability. I know Starscream is a lot more verbose, so I naturally assumed there's a way somehow to add that.
I worked with it before using `ActionCableClient`.

Thanks again!
