### ISSUE TITLE
can't pass parameters from the client side to the server side when creating a subscription

### ISSUE THREAD

**Issue by guolijun** [danielrhodes/Swift-ActionCableClient#2]

**Comment by danielrhodes** [comment]
https://github.com/danielrhodes/Swift-ActionCableClient/blob/master/Pod/Classes/ActionCableClient.swift#L203 You can by using a `ChannelIdentifier`. Be warned this isn't really passing parameters as the identifier literally becomes part of how the channel is identified, so when you send messages from the server to the client, you need to specify those params. If you are looking for authentication, using the headers is better (in my opinion).

**Comment by guolijun** [comment]
ok, thanks
