### ISSUE TITLE
Channel action fired without errors without internet connection

### ISSUE THREAD

**Issue by bitomule** [danielrhodes/Swift-ActionCableClient#22]
There's something weird. When I call channel.Action without internet connection it doesn't return any error. isSubscribed seems to be true even without internet connection.

Any idea?

Update: Seems like the client doesn't detect the lost connection. How can I add ActionCableClient manually to the project to test it?

What I do is:

- Connect to action cable
- Subscribe to channel
- Kill internet connection
- Send an action
- It's sended without issues, channel.action doesn't fire the expected error

**Comment by danipralea** [comment]
I found out that the `onConnect` and `onDisconnect` blocks don't get called.
What I used was subscribing to Starscream notifications:

```swift
import Starscream

    func addWebSocketsNotifications() {
        NotificationCenter.default.addObserver(self, selector: #selector(webSocketConnected(_:)), name: NSNotification.Name(rawValue: WebsocketDidConnectNotification), object: nil)
        
        NotificationCenter.default.addObserver(self, selector: #selector(webSocketDisconnected(_:)), name: NSNotification.Name(rawValue: WebsocketDidDisconnectNotification), object: nil)
    }
    
    func webSocketConnected(_ notification: NSNotification) {
        print("\(self.className): web socket connected")
        if let roomChannel = webSocketsRoomChannel, roomChannel.isSubscribed == false {
            subscribeToWebsocketChannel()
        }
        updateTextViewAndLeftButton()
    }
    
    func webSocketDisconnected(_ notification: NSNotification) {
        print("\(self.className): web socket disconnected")
        updateConnectingIndicator(visible: true)
        updateTextViewAndLeftButton()
    }
```

You can try using this. Although I get an error when trying to send a message without a connection.

**Comment by danielrhodes** [comment]
@bitomule The client will take the message and keep retrying the connection and send the message if there is a successful reconnection. You can change this behavior.

**Comment by bitomule** [comment]
@danielrhodes how do I change that? I already handle trying again when connection is restored.

**Comment by danielrhodes** [comment]
when you create a channel:

```swift
client.create("ChannelName", identifier: nil, autoSubscribe: true, bufferActions: false)
```

That will then mean that if it can't send an action immediately it should throw an error. However, be warned that ActionCable does not acknowledge actions, so there is no guarantee the server received it even though the connection may appear as alive on the websocket level.

**Comment by bitomule** [comment]
I already have buffer actions disabled but still doesn't get the error. Is there any way I can ping ws before sending an action to be sure actions are only sended when connection is working?

**Comment by bitomule** [comment]
Ok, the issues seems to be I was testing in the simulator. Testing in device seems to report connected an disconnected as expected.

**Comment by danielrhodes** [comment]
@bitomule That's odd. I don't think there should be any substantial difference between the two.

**Comment by bitomule** [comment]
@danielrhodes I think the issue was killing macbook wifi connection instead of plane mode inside the simulator.
