### ISSUE TITLE
Authentication Question

### ISSUE THREAD

**Issue by daande** [danielrhodes/Swift-ActionCableClient#3]
What type of headers would I need to set for authentication with this?  Do I just need to pass a users.id? 

```
client.headers = [
    "Authorization": "sometoken"
]
```

Rails Log:

```
Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2016-04-14 18:47:13 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
  ESC[1mESC[36mUser Load (1.3ms)ESC[0m  ESC[1mESC[34mSELECT  "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT $1ESC[0m  [["LIMIT", 1]]
An unauthorized connection attempt was rejected
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
```

XCode Log:

```
ActionCableClient.TransmitError.NotConnected
Connected!
Disconnected!
```

**Comment by danielrhodes** [comment]
This is my preferred approach in using the Authorization header, but it is entirely up to you. ActionCable does not provide any built in ways to authenticate, so you need to create your own.

**Comment by daande** [comment]
@danielrhodes Could you provide me with some sample code on the server side.  Right now in my app/channels/application_cable/connection.rb I have this:

```
def connect
      self.current_user = find_verified_user
      logger.add_tags 'ActionCable', current_user.name
    end

    protected
      def find_verified_user
        if verified_user = User.find_by(id: cookies.signed['user.id'])
          verified_user
        else
          reject_unauthorized_connection
        end
      end
```

That is for my webapp It look like I need to modify something for this ios app to get the user id?

**Comment by danielrhodes** [comment]
So first of all, in the above code snippet you are using cookies, but the WebSocket request is not going to contain any cookies.

Although you can use the user ID, I would highly recommend at the very least passing something like a generated token in the Authorization header and not the user ID as it's quite insecure the way you have it.

Nonetheless, here's how you would do it with a user ID:
```ruby
def connect
      self.current_user = find_verified_user
      logger.add_tags 'ActionCable', current_user.name
end

protected
def find_verified_user
    user_id = request.headers['HTTP_AUTHORIZATION']
    if verified_user = User.find_by(user_id)
       verified_user
    else
       reject_unauthorized_connection
    end
end
```
For example for how you would handle this in Rails with a token, reference the following:
https://www.codeschool.com/blog/2014/02/03/token-based-authentication-rails/

Thus, I think that would turn into something like:

```ruby
include ActionController::HttpAuthentication::Token::ControllerMethods

def connect
    self.current_user = find_verified_user
    reject_unauthorized_connection if self.current_user.nil?
end

protected

def find_verified_user
    authenticate_or_request_with_http_token do |token, options|
      User.find_by(auth_token: token)
    end
end
```

**Comment by daande** [comment]
Yes, I agree with you. I currently login on the iOS app using OAUTH2 there i generate a token.  I just need to modify the code abit and I didnt realize I was only using a user id I guess because when I first started implementing this this I missed that, so thanks for pointing that out for me.

**Comment by daande** [comment]
@danielrhodes Thanks for your help I am all set!

**Comment by masudhossain** [comment]
Sorry to bring back a dead thread, but would I need to do anything extra to my sessioncontroller or applicationcontroller if i wanna use this code in my connection.rb

include ActionController::HttpAuthentication::Token::ControllerMethods

```
def connect
    self.current_user = find_verified_user
    reject_unauthorized_connection if self.current_user.nil?
end

protected

def find_verified_user
    authenticate_or_request_with_http_token do |token, options|
      User.find_by(auth_token: token)
    end
end
```


My sessionscontroller is relatively simple right now. 


```
class SessionsController < ApplicationController
  def new 
    @disable_nav = true
  end 

  def create
    user = User.find_by(email: session_params[:email].downcase)
    respond_to do |format|
      if user && user.authenticate(session_params[:password])
        session[:user_id] = user.id
        cookies.permanent[:user_id] = user.id
        format.html { redirect_to conversations_path }
        format.json { render json: { success: true, user: user }, status: :ok }
      else
        format.html {
          flash[:notice] = 'Incorrect user or password'
          render 'new'
        }
        format.json {
          render json: { success: false, error: 'Incorrect user or password' }, status: :unprocessable_entity
        }
      end
    end
  end

  def destroy
    session.delete(:user_id)
    cookies.delete(:user_id)
    reset_session
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit!
  end
end

```
