### ISSUE TITLE
roomChannel.onReceive method not getting called

### ISSUE THREAD

**Issue by mansishah278** [danielrhodes/Swift-ActionCableClient#30]
I am sending two parameters while creating the roomChannel and it is successfully subscribed, so onSubscribed is called but I am not able to receive messages, i.e onReceive method is not getting called.
@danielrhodes

**Comment by mansishah278** [comment]
`client.onConnected = {

            // Create the Room Channel
            let parameters = [
                "token": token,
                "id": aID
            ]
            let roomChannel = client.create(ADDConstants.ActionCable.roomChannelName, identifier: parameters, autoSubscribe: true, bufferActions: true)
            
            // Channel callbacks
            roomChannel.onReceive = { dict in
                print(dict)
            }
            roomChannel.onSubscribed = {
                print("subscribed")
            }
            roomChannel.onUnsubscribed = {
                print("Unsubscribed")
            }
            roomChannel.onRejected = {
                print("Rejected")
            }
            
        }`

**Comment by mansishah278** [comment]
@danielrhodes

**Comment by ngbsoftware** [comment]
I'm having the same issue. @mansishah278 Did you solve this issue? Thanks

**Comment by mansishah278** [comment]
@ngbsoftware Nope, I am not able to solve it

**Comment by danielrhodes** [comment]
@ngbsoftware @mansishah278 Are you both using identifier parameters when creating the channel? If you don't include these parameters, does it work? From what I've seen in the past, the parameters included when creating a channel make that combination unique. Therefore, to send a message that will be received by that channel, you would have to send a message to that channel with those parameters.

**Comment by mansishah278** [comment]
@danielrhodes 
1 - yes I am using identifier params
It was observed as you stated, any how we could not pass same identifier params while sending message to the channel but got a work around for it

So concluding, to receive data in onReceive method, we need to send message to the channel with the same identifier params that we used while subscribing. Thanks 👍
