### ISSUE TITLE
Action Cable on receive method is not called

### ISSUE THREAD

**Issue by MandeepSingh1** [danielrhodes/Swift-ActionCableClient#38]
Hello Daniel am using the action cable, I will explain you the scenario for the onReceive method not called.

When we start the application then the action cable is working fine, But if I logout from my application and then login from different user then the action cable of onReceive method is not called. I don't understand what happens but if I kill the application and then start it again. Then the action cables onReceive method will work. I don't know what am doing wrong.

Can you suggest me what I have to do.

**Comment by mansi-cherry** [comment]
@danielrhodes onReceive method is not called when message is broadcasted as soon as channel is subscribed..

**Comment by MandeepSingh1** [comment]
Hi @mansi-cherry , can you explain me your scenario how you are using the action cables. May be I can help you. I have resolved my issue.

**Comment by mansi-cherry** [comment]
@MandeepSingh1 How did you solve this?

**Comment by mansi-cherry** [comment]
I have used action cable in multiple cases in my app, but for one time, message from the rails is broadcasted as soon as my channel is subscribed. So for that case I am not getting onReceive callback. Everywhere else it is working fine!

**Comment by MandeepSingh1** [comment]
In my case when ever am login in my app and then I call the cables to connect. But when I do the logout, then I disconnect the action cables.

**Comment by MandeepSingh1** [comment]
Am calling this method in did finish launch with options

func connectTheActionCable() {
        
        if let actionCableURL = URL(string: "your server url") {
            
            actionCableClient = ActionCableClient(url: actionCableURL)
            
            actionCableClient.willConnect = {
                print("Will Connect")
            }
            
            actionCableClient.onConnected = {
                print("Connected to \(self.actionCableClient.url)")
                
            }
            
            actionCableClient.onDisconnected = {(error: ConnectionError?) in
                print("Disconected with error: \(String(describing: error))")
            }
            
            actionCableClient.onRejected = {
                print("Connected to \(self.actionCableClient.url)")
            }
            
            actionCableClient.willReconnect = {
                print("Reconnecting to \(self.actionCableClient.url)")
                return true
            }
            
            actionCableClient.connect()
        }
    }

**Comment by mansi-cherry** [comment]
No, I have no such issue related to connecting and disconnecting.

**Comment by MandeepSingh1** [comment]
@mansi-cherry , can you show me your code may be I can help you in code rather then discussing the point in comments. Have you pass the same function name and channel name in your code?

**Comment by mansi-cherry** [comment]
`
    func subscribeChannel(forAuthToken token: String, aID: String) {
        
        guard let client = client else {return}
        
        client.onConnected = { [weak self] _ in
            guard let strongSelf = self else {return}

            /// Create the Room Channel
            let parameters = [
                "actionCableAuthToken": token,
                "Id": aID
            ]
            strongSelf.wrChannel = client.create(ADDConstants.ActionCable.wrChannelName, identifier: parameters, autoSubscribe: true, bufferActions: true)
            
            /// Channel callbacks
            strongSelf.wrChannel?.onReceive = { [weak self] result, error in
                guard let strongSelf = self, let result = result else {return}
                strongSelf.didReceiveJSON?(JSON(result))
            }
        }
    }`

**Comment by MandeepSingh1** [comment]
please call this methods also and check whether your method is getting connected or not, you have to replace the roomFollowUser with client. Check whether your channel is subscribing properly or not. 

 // A channel has successfully been subscribed to.
        roomFollowUser.onSubscribed = {
            print("successfully followParticularUser subscribed")
        }
        
        // A channel was unsubscribed, either manually or from a client disconnect.
        roomFollowUser.onUnsubscribed = {
            print("Unsubscribed")
        }
        
        // The attempt at subscribing to a channel was rejected by the server.
        roomFollowUser.onRejected = {
            print("Rejected")
        }

**Comment by mansi-cherry** [comment]
Yes I checked that, by printing the onSubscribed CallBacks

**Comment by MandeepSingh1** [comment]
Basically when am facing this issue. When I logout from my application and then try to login from different user then the action cable of onReceive method is not getting called thats my scenario and rails methods is working fine.

**Comment by mansi-cherry** [comment]
yeah mine is not that kind of scenario, but the issue is same "onReceive not called"

**Comment by MandeepSingh1** [comment]
When you are trying to subscribe the channel in viewDidLoad, viewWillAppear? Or May be you are trying to subscribe the multiple channels simultaneously?

**Comment by MandeepSingh1** [comment]
My another reason is am trying

**Comment by mansi-cherry** [comment]
I subscribe in viewWillAppear and unsubscribe in viewWillDisAppear

**Comment by MandeepSingh1** [comment]
Do you have multiple channels to subscribe in viewWillAppear or just a single channel?

**Comment by mansi-cherry** [comment]
Single channel only

**Comment by MandeepSingh1** [comment]
Try to subscribe the channel in 

override func viewDidAppear(_ animated: Bool) {
        self.addActionCableSubscribeChannels()
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        ActionCableClientSingleton.sharedInstance.roomFollowUser.unsubscribe()
    }

**Comment by mansi-27** [comment]
Hey @danielrhodes I am using Rails 5 version.
Can it be the reason that broadcast happens as soon as subscribed the channel, and hence onReceive is not called, may be async operations don't work?

**Comment by johnmcauley** [comment]
Hey @mansi-cherry - we are having the same issues, did you find a resolution?

**Comment by mansi-27** [comment]
@johnmcauley Actually in my case, I was maintaining the action cable instance as a Singleton instance. So it was not handled properly from my side
Another thing is that there are 2 ways to initialise action cable client, for me one of them didn't seem to work so I used the another way. Had I have the access of source code now, I would have shared the code snippet.
