### ISSUE TITLE
Clear channels

### ISSUE THREAD

**Issue by allaire** [danielrhodes/Swift-ActionCableClient#39]
Is there a way to clear autoSubscribed channels, let say when a user sign out? I can disconnect the websocket, but when I reconnect it when the other user log in, old subscriptions remain. Note that I'm using a Singleton ActionCable Manager, so maybe I should just reset the singleton instance?

**Comment by mansi-27** [comment]
Hey @allaire, Did you try `yourChannel.unsubscribe()` ?

**Comment by allaire** [comment]
@mansi-cherry Yeah I finally made a ActionCableManager class, and manage an array of subscriptions. When the user signs out, I loop and unsubscribe each channel.
