### ISSUE TITLE
masked and rsv data is not currently supported

### ISSUE THREAD

**Issue by Chakery** [danielrhodes/Swift-ActionCableClient#5]
After the success of login, first try socket connection and success. when I logout and re-login, and connection socket again, I got below:

ActionCableClient.ConnectionError.ProtocolViolation(Error Domain=WebSocket Code=1002 "masked and rsv data is not currently supported" UserInfo={NSLocalizedDescription=masked and rsv data is not currently supported})

please help...

**Comment by Chakery** [comment]
well, because I forgot disconnect and reconnect, so cause this problem. 
Thx for your Swift-ActionCableClient.

**Comment by danielrhodes** [comment]
I have also seen that before under similar circumstances. It is coming from the underlying websocket library, which I plan to switch out soon.

**Comment by Chakery** [comment]
disconnected it before you reconnect and you won't face this problem...

**Comment by Preen** [comment]
Is this solved? I mean the solution "disconnect before you reconnect" is not a long term solution imo...?

When is it planned to be switched out?
