### ISSUE TITLE
minimum deployment target

### ISSUE THREAD

**Issue by selfcreator** [danielrhodes/Swift-ActionCableClient#9]
pod 'ActionCableClient', :git => 'https://github.com/danielrhodes/Swift-ActionCableClient', :branch => 'swift3'

Specs satisfying the `ActionCableClient (from`https://github.com/danielrhodes/Swift-ActionCableClient`, branch `swift3`)` dependency were found, but they required a higher minimum deployment target.

Seems it requires iOS 9.0
Why?
Before Swift3, this project supports >= 8.0 right?
Current my project support OS >= 8.0

**Comment by danielrhodes** [comment]
I can look into changing this if it is still an issue.

Otherwise, take a look at [this](https://mixpanel.com/trends/#report/ios_10), which shows that < iOS 9 represents under 5% of devices right now.

**Comment by danielrhodes** [comment]
Fixed.

**Comment by selfcreator** [comment]
Thanks, @danielrhodes. We've already upgrade the deploy target to iOS 9 for our app.
